version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: ikapro_mysql5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ikalist
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: ikachan
      MYSQL_PASSWORD: ikagirl
      TZ: 'Asia/Tokyo'
    volumes:
      - ./sql/data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    restart: always