# Generated by Django 2.2.7 on 2019-12-12 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('coler_code', models.CharField(max_length=7, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('finished_flag', models.BooleanField(default=False)),
                ('deadline', models.TimeField(null=True)),
                ('important', models.CharField(choices=[('0', 'Nothing'), ('1', 'Low'), ('2', 'Medium'), ('3', 'High')], default=0, max_length=1)),
                ('memo', models.CharField(max_length=255, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo_Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Label')),
                ('todo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Todo')),
            ],
        ),
    ]
